name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 10.27.0 }
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'pnpm' }
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm build
      - name: Create Pull Request
        run: |
          if [ -z "$(gh pr list --state open --base main --head ${{ github.ref }})" ]; then
            gh pr create --base main --head ${{ github.ref }} --title "Automated PR from CI" --body "This PR was created automatically after successful CI checks.";
          fi
